export enum RecipeIngredient {
  kuracie_maso = "kuracie_maso",
  sojova_omacka = "sojova_omacka",
  voda = "voda",
  kukuricny_skrob = "kukuricny_skrob",
  ryzove_vino = "ryzove_vino",
  ryzovy_ocot = "ryzovy_ocot",
  cukor = "cukor",
  olej = "olej",
  sol = "sol",
  zazvor = "zazvor",
  arasidy = "arasidy",
  chilli_papricka = "chilli_papricka",
  parky = "parky",
  zemiaky = "zemiaky",
  cibula = "cibula",
  tuk = "tuk",
  hladka_muka = "hladka_muka",
  mlieko = "mlieko",
  paprika_mleta_sladka = "paprika_mleta_sladka",
  vyvar = "vyvar",
  korenie_cierne_mlete = "korenie_cierne_mlete",
}
